# Generated by Django 5.1 on 2024-08-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=10)),
                ('Line_ID', models.CharField(max_length=50)),
                ('email_add', models.EmailField(max_length=254, unique=True)),
                ('industry', models.CharField(max_length=100)),
            ],
        ),
    ]
