# Generated by Django 5.1 on 2024-08-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='contact_choice',
            field=models.CharField(choices=[('interested', '有興趣，可以再後續規劃與詳談'), ('no_contact', '不用聯繫我，先參考即可')], default='no_contact', max_length=20),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='web_type',
            field=models.CharField(blank=True, choices=[('single_page', '一頁式網站'), ('corporate', '形象網站')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
