# Generated by Django 5.1 on 2024-08-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_webservices_clientinfo_ps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='web_type',
            field=models.CharField(blank=True, choices=[('single_page', '一頁式網站'), ('template_corporate', '套版形象網站'), ('half_template_corporate', '半套版形象網站')], max_length=50),
        ),
    ]
